project:
  type: website

website:
  title: "quarto_web_test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "A"
        file: PCA_GTEx_scLiver_v2.ipynb

  sidebar:
    style: "docked"
    search: True
    contents:
      - section: "all"
        contents:
          - section: "DL"
            contents:
              - about.qmd
              - PCA_GTEx_scLiver_v2.ipynb
          - section: "Basics"
            contents:
              - PCA_GTEx_scLiver_v3.ipynb
              - PCA_GTEx_scLiver_v4.ipynb



        

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



